Controllers/IgraciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PINProject.Data;
using Rukomet.Models;

namespace Rukomet.Controllers
{
    public class IgraciController : Controller
    {
        private readonly ApplicationDbContext _context;

        public IgraciController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Igraci
        public async Task<IActionResult> Index(string search)
        {
            if (!String.IsNullOrEmpty(search))
            {
                ViewBag.Search = search;

                var igraci = from igrac in _context.Igrac
                              select igrac;

                igraci = igraci.Where(igrac => igrac.Ime.Contains(search));
                return View(igraci.ToList());
            }
            return View(await _context.Igrac.ToListAsync());
        }

        // GET: Igraci/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Igrac == null)
            {
                return NotFound();
            }

            var igrac = await _context.Igrac
                .FirstOrDefaultAsync(m => m.Id == id);
            if (igrac == null)
            {
                return NotFound();
            }

            return View(igrac);
        }

        // GET: Igraci/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Igraci/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Ime,Prezime,BrojDresa,Klub")] Igrac igrac)
        {
            if (ModelState.IsValid)
            {
                _context.Add(igrac);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(igrac);
        }

        // GET: Igraci/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Igrac == null)
            {
                return NotFound();
            }

            var igrac = await _context.Igrac.FindAsync(id);
            if (igrac == null)
            {
                return NotFound();
            }
            return View(igrac);
        }

        // POST: Igraci/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Ime,Prezime,BrojDresa,Klub")] Igrac igrac)
        {
            if (id != igrac.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(igrac);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IgracExists(igrac.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(igrac);
        }

        // GET: Igraci/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Igrac == null)
            {
                return NotFound();
            }

            var igrac = await _context.Igrac
                .FirstOrDefaultAsync(m => m.Id == id);
            if (igrac == null)
            {
                return NotFound();
            }

            return View(igrac);
        }

        // POST: Igraci/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Igrac == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Igrac'  is null.");
            }
            var igrac = await _context.Igrac.FindAsync(id);
            if (igrac != null)
            {
                _context.Igrac.Remove(igrac);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IgracExists(int id)
        {
          return _context.Igrac.Any(e => e.Id == id);
        }
    }
}

Controllers/KluboviController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PINProject.Data;
using Rukomet.Models;

namespace Rukomet.Controllers
{
    public class KluboviController : Controller
    {
        private readonly ApplicationDbContext _context;

        public KluboviController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Klubovi
        public async Task<IActionResult> Index(string search)
        {
            if (!String.IsNullOrEmpty(search))
            {
                ViewBag.Search = search;

                var klubovi = from klub in _context.Klub
                              select klub;

                klubovi = klubovi.Where(klub => klub.ImeKluba.Contains(search));
                return View(klubovi.ToList());
            }
              return View(await _context.Klub.ToListAsync());
        }

        // GET: Klubovi/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Klub == null)
            {
                return NotFound();
            }

            var klub = await _context.Klub
                .FirstOrDefaultAsync(m => m.Id == id);
            if (klub == null)
            {
                return NotFound();
            }

            return View(klub);
        }

        // GET: Klubovi/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Klubovi/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ImeKluba,GradKluba,BrojTrofeja")] Klub klub)
        {
            if (ModelState.IsValid)
            {
                _context.Add(klub);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(klub);
        }

        // GET: Klubovi/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Klub == null)
            {
                return NotFound();
            }

            var klub = await _context.Klub.FindAsync(id);
            if (klub == null)
            {
                return NotFound();
            }
            return View(klub);
        }

        // POST: Klubovi/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ImeKluba,GradKluba,BrojTrofeja")] Klub klub)
        {
            if (id != klub.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(klub);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KlubExists(klub.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(klub);
        }

        // GET: Klubovi/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Klub == null)
            {
                return NotFound();
            }

            var klub = await _context.Klub
                .FirstOrDefaultAsync(m => m.Id == id);
            if (klub == null)
            {
                return NotFound();
            }

            return View(klub);
        }

        // POST: Klubovi/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Klub == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Klub'  is null.");
            }
            var klub = await _context.Klub.FindAsync(id);
            if (klub != null)
            {
                _context.Klub.Remove(klub);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KlubExists(int id)
        {
          return _context.Klub.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Handball</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PINProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/css1.css">
    <link href='C:\Users\ana.grlic\Documents\Privatno\Faks\PIN\Projekt\05_02_2023\PINProject\wwwroot\css'>

</head>
<body  style="background-image: url(../../css/ba3.jpg)">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Handball</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Klubovi" asp-action="Index">Klubovi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Igraci" asp-action="Index">Igraci</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Handball - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>